name: $(Build.Major).$(Build.Minor).0.$(Build.BuildId)
trigger:
- master
resources:
  repositories:
  - repository: self
variables:
  Build.Major: 1
  Build.Minor: 4
  Build.Patch: 0
  Build.Revision: $(Build.BuildId)
  Build.Configuration: 'Release'
  VersioningScheme: 'byPrereleaseNumber'


jobs:
- job: Windows
  pool: 'Hosted VS2017'
  steps:
  - template: steps-build-core.yml
  - template: steps-build-samples.yml
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()

####
# Needs to be disabled due to: https://developercommunity.visualstudio.com/content/problem/423843/condaenvironment.html
####
# - job: macOS
#   pool: 'Hosted macOS'
#   steps:
#   - template: steps-build-core.yml
#   - template: steps-build-samples.yml
# - job: Linux
#   pool: 'Hosted Ubuntu 1604'
#   steps:
#   - template: steps-build-core.yml
#   - template: steps-build-samples.yml

