name: $(Build.Major).$(Build.Minor).$(BuildId)
trigger:
- master

schedules:
- cron: "0 9 * * Sat"
  displayName: 'Build for Component Governance'
  branches:
    include:
    - master
  always: true

resources:
  repositories:
  - repository: self
variables:
  Build.Major: 1
  Build.Minor: 5
  Build.Patch: $(Build.BuildId)
  Build.Configuration: 'Release'
  VersioningScheme: 'byPrereleaseNumber'


jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: steps-build-core.yml
  - template: steps-build-samples.yml
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()

####
# Needs to be disabled due to: https://developercommunity.visualstudio.com/content/problem/423843/condaenvironment.html
####
# - job: macOS
#   pool: 'Hosted macOS'
#   steps:
#   - template: steps-build-core.yml
#   - template: steps-build-samples.yml
# - job: Linux
#   pool: 'Hosted Ubuntu 1604'
#   steps:
#   - template: steps-build-core.yml
#   - template: steps-build-samples.yml

