name: $(Build.Major).$(Build.Minor).$(BuildId)
trigger:
- master

schedules:
- cron: "0 9 * * Sat"
  displayName: 'Build for Component Governance'
  branches:
    include:
    - master
  always: true

resources:
  repositories:
  - repository: self
variables:
  Build.Major: 2
  Build.Minor: 0
  Build.Patch: $(Build.BuildId)
  Build.Configuration: 'Release'
  VersioningScheme: 'byPrereleaseNumber'


jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  - template: steps-build-core.yml
  - template: steps-build-samples.yml
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()

