name: $(Build.Major).$(Build.Minor).$(Date:yyMM).$(DayOfMonth)$(Rev:rr)
trigger:
- master
resources:
  repositories:
  - repository: self
variables:
  Build.Major: 1
  Build.Minor: 4
  Build.Configuration: 'Release'
  Assembly.Version: $(Build.BuildNumber)
  Assembly.Constants: 'SIGNED'
  VersioningScheme: 'byBuildNumber'
  DllsToScan: 'src\bin\Release\*\*.dll'

jobs:
- job: Windows
  pool: 'Hosted VS2017'
  steps:
  - template: steps-build-core.yml
  - template: steps-build-samples.yml
  - template: steps-sign.yml
  - template: steps-sdl-tools.yml
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
